export const movementLibrary = [
  {
    code: 'wu_cat_cow',
    name: 'Cat-Cow Spine Prep',
    category: 'warmup',
    difficulty: 'beginner',
    equipment: 'bodyweight',
    targetMuscles: ['spine', 'core'],
    cues: ['Move slowly with breath', 'Keep shoulders away from ears'],
  },
  {
    code: 'wu_arm_circles',
    name: 'Arm Circles',
    category: 'warmup',
    difficulty: 'beginner',
    equipment: 'bodyweight',
    targetMuscles: ['shoulders', 'upper back'],
    cues: ['Light tension only', 'Small to medium circles first'],
  },
  {
    code: 'wu_leg_swings',
    name: 'Front-to-Back Leg Swings',
    category: 'warmup',
    difficulty: 'beginner',
    equipment: 'bodyweight',
    targetMuscles: ['hips', 'hamstrings'],
    cues: ['Hold onto support', 'Keep core braced'],
  },
  {
    code: 'wu_glute_bridge',
    name: 'Glute Bridge Activation',
    category: 'warmup',
    difficulty: 'beginner',
    equipment: 'bodyweight',
    targetMuscles: ['glutes', 'hamstrings'],
    cues: ['Drive through heels', 'Squeeze glutes at top'],
  },
  {
    code: 'wu_worlds_greatest',
    name: "World's Greatest Stretch",
    category: 'warmup',
    difficulty: 'beginner',
    equipment: 'bodyweight',
    targetMuscles: ['hips', 'thoracic spine'],
    cues: ['Reach long through the spine', 'Pause briefly in each position'],
  },
  {
    code: 'main_goblet_squat',
    name: 'Goblet Squat',
    category: 'main',
    difficulty: 'beginner',
    equipment: 'dumbbell',
    targetMuscles: ['quads', 'glutes', 'core'],
    cues: ['Keep chest tall', 'Knees track over toes'],
  },
  {
    code: 'main_bodyweight_squat',
    name: 'Bodyweight Squat',
    category: 'main',
    difficulty: 'beginner',
    equipment: 'bodyweight',
    targetMuscles: ['quads', 'glutes'],
    cues: ['Push hips back then down', 'Balance weight mid-foot'],
  },
  {
    code: 'main_rdl',
    name: 'Romanian Deadlift',
    category: 'main',
    difficulty: 'intermediate',
    equipment: 'dumbbell',
    targetMuscles: ['hamstrings', 'glutes', 'back'],
    cues: ['Soft knees', 'Hinge at hips with flat back'],
  },
  {
    code: 'main_hip_hinge',
    name: 'Hip Hinge Pattern',
    category: 'main',
    difficulty: 'beginner',
    equipment: 'bodyweight',
    targetMuscles: ['hamstrings', 'glutes'],
    cues: ['Maintain neutral spine', 'Reach hips back'],
  },
  {
    code: 'main_pushup',
    name: 'Push-Up',
    category: 'main',
    difficulty: 'intermediate',
    equipment: 'bodyweight',
    targetMuscles: ['chest', 'triceps', 'core'],
    cues: ['Elbows at ~45°', 'Brace core to prevent sagging'],
  },
  {
    code: 'main_incline_pushup',
    name: 'Incline Push-Up',
    category: 'main',
    difficulty: 'beginner',
    equipment: 'bodyweight',
    targetMuscles: ['chest', 'triceps', 'shoulders'],
    cues: ['Use a stable surface', 'Move as one plank'],
  },
  {
    code: 'main_single_arm_row',
    name: 'Single-Arm Dumbbell Row',
    category: 'main',
    difficulty: 'intermediate',
    equipment: 'dumbbell',
    targetMuscles: ['back', 'biceps', 'core'],
    cues: ['Pull elbow to hip', 'Keep spine long'],
  },
  {
    code: 'main_machine_row',
    name: 'Seated Machine Row',
    category: 'main',
    difficulty: 'beginner',
    equipment: 'machine',
    targetMuscles: ['back', 'biceps'],
    cues: ['Set shoulders down and back', 'Control the return'],
  },
  {
    code: 'main_overhead_press',
    name: 'Dumbbell Overhead Press',
    category: 'main',
    difficulty: 'intermediate',
    equipment: 'dumbbell',
    targetMuscles: ['shoulders', 'triceps', 'core'],
    cues: ['Brace ribs down', 'Press slightly forward and up'],
  },
  {
    code: 'main_split_squat',
    name: 'Split Squat',
    category: 'main',
    difficulty: 'intermediate',
    equipment: 'bodyweight',
    targetMuscles: ['quads', 'glutes', 'balance'],
    cues: ['Front knee over mid-foot', 'Light pressure on back toe'],
  },
  {
    code: 'main_reverse_lunge',
    name: 'Reverse Lunge',
    category: 'main',
    difficulty: 'beginner',
    equipment: 'bodyweight',
    targetMuscles: ['quads', 'glutes'],
    cues: ['Step back softly', 'Stay tall through torso'],
  },
  {
    code: 'main_plank',
    name: 'Plank Hold',
    category: 'main',
    difficulty: 'beginner',
    equipment: 'bodyweight',
    targetMuscles: ['core', 'shoulders'],
    cues: ['Squeeze glutes', 'Push the floor away'],
  },
  {
    code: 'opt_side_plank',
    name: 'Side Plank',
    category: 'optional',
    difficulty: 'intermediate',
    equipment: 'bodyweight',
    targetMuscles: ['obliques', 'shoulders'],
    cues: ['Stack shoulders and hips', 'Keep neck long'],
  },
  {
    code: 'opt_dead_bug',
    name: 'Dead Bug',
    category: 'optional',
    difficulty: 'beginner',
    equipment: 'bodyweight',
    targetMuscles: ['core', 'hip flexors'],
    cues: ['Press low back into floor', 'Move opposite arm and leg slowly'],
  },
  {
    code: 'opt_banded_pull_apart',
    name: 'Banded Pull-Apart',
    category: 'optional',
    difficulty: 'beginner',
    equipment: 'bodyweight',
    targetMuscles: ['upper back', 'shoulders'],
    cues: ['Arms stay straight', 'Squeeze shoulder blades together'],
  },
  {
    code: 'opt_machine_leg_press',
    name: 'Machine Leg Press',
    category: 'optional',
    difficulty: 'beginner',
    equipment: 'machine',
    targetMuscles: ['quads', 'glutes'],
    cues: ['Control depth', 'Keep feet flat'],
  },
  {
    code: 'opt_farmers_carry',
    name: "Farmer's Carry",
    category: 'optional',
    difficulty: 'intermediate',
    equipment: 'dumbbell',
    targetMuscles: ['grip', 'core', 'upper back'],
    cues: ['Walk tall', 'Short, controlled steps'],
  },
];

export default movementLibrary;
